server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://136.244.95.253:5432/cool_db
    username: admin
    password: "postgres_master"
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
