server:
  port: 80
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://136.244.95.253:5432/cool_db
    username: admin
    password: "postgres_master"

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true



#  sql:
#    init:
#      data-locations: data.sql
#logging:
#  level:
#    root: trace
